# Generated by Django 4.2.11 on 2026-02-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['chunk_index']},
        ),
    ]
