# Generated by Django 4.2.11 on 2026-02-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_pdfsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFSubmission',
            new_name='DocumentSubmission',
        ),
    ]
