# Generated by Django 4.2.11 on 2026-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_rename_pdfsubmission_documentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmission',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
